### PR TITLE
Fix ref type mapping

### LINKED ISSUE #23: File references are not considered of type 'file'
1) What version of the module is the issue happening on? Does the issue happen on latest version?

0.10.0

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)

10.15.3

3) Sample source code or steps to reproduce

References that use the `file:` prefix are not correctly marked as files. This is due to the boolean check at https://github.com/bojand/json-schema-deref-sync/blob/10b1b3b94ffa27d8312537bbf540a59ac7aeaf27/lib/utils.js#L36.

This check performs this boolean `(validUrl.isUri(val) && val.indexOf('file:') === '0')`. However, the value of `val.indexOf('file:')` is a number not a string. When using exactly equals (`===`) no type conversion will occur. This will make the test fail and incorrectly mark this as not a file.

Example: `file:path/file.json#/parent/child`

### LINKED ISSUE #28: YAML files are ignored and treated as local refs
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.10.1

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
NodeJS v10.16.0 on MacOS Mojave

3) Sample source code or steps to reproduce
Use YAML file refs
```json
$ref: "./validator/countries.yaml#/routes/base"
```
[countries.yaml.zip](https://github.com/cvent/json-schema-deref-sync/files/3596023/countries.yaml.zip)

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
YAML files are ignored and treated as local refs, as a result I'm getting this stack trace
```stack
TypeError: Cannot read property 'countries.yaml#' of undefined
  at /home/api/node_modules/json-schema-deref-sync/lib/utils.js:84:17
  at Array.reduce (<anonymous>)
  at Object.getRefPathValue (/home/api/node_modules/json-schema-deref-sync/lib/utils.js:83:15)
  at getRefSchema (/home/api/node_modules/json-schema-deref-sync/lib/index.js:99:18)
  at Object.<anonymous> (/home/api/node_modules/json-schema-deref-sync/lib/index.js:236:24)
  at walker (/home/api/node_modules/traverse/index.js:190:22)
  at /home/api/node_modules/traverse/index.js:208:29
  at Array.forEach (<anonymous>)
  at forEach (/home/api/node_modules/traverse/index.js:298:31)
  at walker (/home/api/node_modules/traverse/index.js:203:13)
  at /home/api/node_modules/traverse/index.js:208:29
  at Array.forEach (<anonymous>)
  at forEach (/home/api/node_modules/traverse/index.js:298:31)
  at walker (/home/api/node_modules/traverse/index.js:203:13)
  at walk (/home/api/node_modules/traverse/index.js:226:7)
  at Traverse.forEach (/home/api/node_modules/traverse/index.js:50:18)
  at derefSchema (/home/api/node_modules/json-schema-deref-sync/lib/index.js:223:27)
  at deref (/home/api/node_modules/json-schema-deref-sync/lib/index.js:310:13)
  at Object.buildSchemaSync (/home/api/node_modules/api-schema-builder/src/index.js:35:26)
  at Object.init (/home/api/node_modules/express-ajv-swagger-validation/src/middleware.js:25:32)
  at Object.<anonymous> (/home/api/dist/server.js:21:28)
  at Generator.next (<anonymous>)
```

I already have a PR ready to fix this issue https://github.com/cvent/json-schema-deref-sync/pull/27

### PR DESCRIPTION
**Pull request by kobik**
Hi, I'm a maintainer of the following packages which are used for performing request and response validation according to API definitions file given in yaml format.
[api-contract-validator](https://github.com/Zooz/api-contract-validator) and [express-ajv-swagger-validation](https://github.com/Zooz/express-ajv-swagger-validation) which are using [api-schema-builder](https://github.com/Zooz/api-schema-builder) underneath in order to build JSON schema for validation using AJV.

We use this great package for dereferencing all refs before passing the schema to AJV.
I'd like to add support for loading referenced YAML files, And this PR comes to handle just that.

Closes #28  and closes #23

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -33,7 +34,12 @@ function getRefType (ref) {
     if (validUrl.isWebUri(val)) {
       return 'web'
     }
-    if ((validUrl.isUri(val) && val.indexOf('file:') === '0') || (val.indexOf('.json') > 0) || isValidPath(val)) {
+    if (
+      (validUrl.isUri(val) && val.startsWith('file:')) ||
+      val.includes('.json') ||
+      val.match(yamlSuffixRegex) ||
+      isValidPath(val.split['#'])
```
Comment (kobik) [inline lib/utils.js]: BTW, `val.split['#']` would always return `undefined`.
what's the purpose of `isValidPath(val.split['#'])`?

File: lib/loaders/file.js [hunk 2]
```diff
@@ -26,9 +27,21 @@ module.exports = function (refValue, options) {
 
   let newValue
   try {
-    var data = fs.readFileSync(filePath)
-    newValue = JSON.parse(data)
-  } catch (e) {}
+    var data = fs.readFileSync(filePath, 'utf8')
+    newValue = parseJson(data) || parseYaml(data)
```
Comment (kibertoad) [inline lib/loaders/file.js]: Is it a good approach to just try parsing both and see which one doesn't fail? Maybe this should be a fallback logic when it is impossible to determine format unambiguously based on filePath extension?

File: lib/utils.js [hunk 3]
```diff
@@ -18,6 +18,7 @@ function getRefValue (ref) {
 }
 exports.getRefValue = getRefValue
 
+const yamlSuffixRegex = /\.ya?ml/ // regex for matching .yaml/.yml files
```
Comment (kibertoad) [inline lib/utils.js]: probably should be case-insensitive as well?

Comment (kobik) [reply lib/utils.js]: i didn't see any special treatment to ref case anywhere, but i've updated the condition to disregard the file extension case

File: lib/loaders/file.js (hunk 2 above)
Comment (kobik) [reply lib/loaders/file.js]: Good suggestion, I currently can't test that because currently a ref would only mapped to file in case it has json, yaml or yml extension

File: lib/loaders/file.js [hunk 4]
```diff
@@ -23,12 +24,31 @@ module.exports = function (refValue, options) {
...
-    var data = fs.readFileSync(filePath)
-    newValue = JSON.parse(data)
-  } catch (e) {}
+    var data = fs.readFileSync(filePath, 'utf8')
+    if (filePathLowerCase.endsWith('.json')) {
+      newValue = parseJson(data) || parseYaml(data)
+    } else if (filePathLowerCase.endsWith('.yml') || filePathLowerCase.endsWith('.yaml')) {
+      newValue = parseYaml(data)
+    } else {
+      newValue = parseJson(data) || parseYaml(data)
```
Comment (scdowney) [inline lib/loaders/file.js]: This seems redundant with the first case? Looks like the first case could just be the .yml/.yaml case and then this else?

Comment (kobik) [reply lib/loaders/file.js]: the intention of this is to handle files with no extension. the question is wether you'd like to support it or not.

File: lib/utils.js (hunk 1 above)
Comment (kobik) [reply lib/utils.js]: Care to explain this guys?

**Comment by simonmeusel** [comment]
I would recommend to add a option to restrict the file formats, to prevent slow parsers or security issues in parsers from having an impact. E. g. when you know you are not using the yml parser.

**Comment by kibertoad** [comment]
@simonmeusel What is left before this can be merged then?

**Comment by simonmeusel** [comment]
I currently do not have access to a computer to really test the code, but I have quickly looked over it and it seems good.

Someone with write access now has to review and merge this. @bojand

**Comment by jcurtis** [comment]
I could see this causes breaking changes so let's bump the major version once merged.

**Comment by kobik** [comment]
Thanks @jcurtis, so what's currently holding us back from merging it?

**Comment by jcurtis** [comment]
@kobik just figuring our package ownership stuff, might take a couple days before this is published

**Comment by jcurtis** [comment]
Tagged as 0.11.0 on GitHub

**Comment by kobik** [comment]
Thanks!

**Comment by kobik** [comment]
@jcurtis it wasn't published to npm yet? 😊

**Comment by jcurtis** [comment]
@kobik correct, still trying to figure things out from an ownership perspective. Please bear with me. 

Alternatively I believe you could point your package.json directly to the git tag, until I can figure out publishing stuff:

```
"json-schema-deref-sync": "cvent/json-schema-deref-sync#v0.11.0"
```

**Comment by kobik** [comment]
NP, just making sure it wasn't forgotten unintentionally.

**Comment by kobik** [comment]
@jcurtis, when are you planning on releasing new version?
I'd really like this to be resolved.

Thanks
